### ISSUE TITLE
Les import ne marchent plus

### ISSUE THREAD

**Issue by Lisa-Baget** [Lisa-Baget/pyanote#3]
Tout marche bien sur le PC, mais des que je passe sur le portable ça me fait des Erreurs car il ne trouve pas le module pyanote... Pourquoi? J'ai besoin que ça passe sur le portable pour la presentation ISN !!!

**Comment by phandaal** [comment]
A la racine de ton projet, rajoute un fichier `setup.py`.

Ce fichier va contenir le code suivant:

```python
from setuptools import setup

setup(
   name='pyanote', # le nom du projet
   version='0.0.0-beta.2', # le numero de version
   description='une courte description.',
   author='ton nom',
   author_email='ton email',
   packages=['pyanote'], # le meme nom qu'en haut
   install_requires=['pygame'] # je crois que tu importes que ça de non standard
)
```
ensuite des que tu as des problemes d'import tu tapes dans le shell:

```
python setup.py develop
````
Ca devrait regler le probleme.

**Comment by Lisa-Baget** [comment]
Ca marche!!!!
